### ISSUE TITLE
Add support for gating on a different check name in try builds

### ISSUE THREAD

**Issue by pietroalbini** [rust-lang/homu#37]
If we switch to Azure Pipelines for rustc we're going to have two pipelines, one for try builds and one for auto builds, and homu doesn't support having different check names at the moment. We need to add that.

**Comment by bryanburgers** [comment]
Would it make sense to key off of Check Suites instead of Check Runs? GitHub is already rolling up the Check Runs into a final status for us via the Check Suite.

Could we use `app.name` or `app.slug`, which remains stable – doesn't change across `try` and `auto` branches – to get the final results, instead of special-casing check run names?

---

### Try ([`f939092`](https://github.com/rust-lang/rust/commit/f939092855377cee8da8b6c47cbfa083cf2f89f2))
#### Check Suites

app.name | app.slug | branch.name
---------|----------|------------
Azure Pipelines | azure-pipelines | try
Travis CI | travis-ci | try

#### Check Runs

name | externalId
-----|-----------
try (macOS dist-x86_64-apple)                      | [8\|288\|e71b0ddf-dd27-435a-873c-e30f86eea377](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_build/results?buildId=288&view=logs&jobId=0dc43f6a-414d-5e5c-43cd-8d26a1671d44)
try (Linux dist-x86_64-linux)                      | [8\|288\|e71b0ddf-dd27-435a-873c-e30f86eea377](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_build/results?buildId=288&view=logs&jobId=75fb7074-5230-5c5b-6df3-8cc660977bc4)
try (macOS dist-x86_64-apple-alt)                  | [8\|288\|e71b0ddf-dd27-435a-873c-e30f86eea377](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_build/results?buildId=288&view=logs&jobId=9b18a8e0-d349-5dff-dec8-879f98f28b96)
try (Linux dist-x86_64-linux-alt)                  | [8\|288\|e71b0ddf-dd27-435a-873c-e30f86eea377](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_build/results?buildId=288&view=logs&jobId=396dc680-0b3a-5910-2395-0c692e01f85b)
try (Windows dist-x86_64-msvc)                     | [8\|288\|e71b0ddf-dd27-435a-873c-e30f86eea377](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_build/results?buildId=288&view=logs&jobId=10c53b70-9ae7-511a-b369-2febdb4c7298)
try (Windows dist-x86_64-msvc-alt)                 | [8\|288\|e71b0ddf-dd27-435a-873c-e30f86eea377](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_build/results?buildId=288&view=logs&jobId=d91b65d8-1798-544d-059f-fe4f3f5f069a)
try                                                | [8\|288\|e71b0ddf-dd27-435a-873c-e30f86eea377](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_build/results?buildId=288)
Travis CI - Branch                                 | [113479224](https://travis-ci.com/rust-lang/rust/builds/113479224)

### Auto ([`8197085`](https://github.com/rust-lang/rust/commit/81970852e172c04322cbf8ba23effabeb491c83c))
#### Check Suites

app.name | app.slug | branch.name
---------|----------|------------
Azure Pipelines | azure-pipelines | auto
Travis CI | travis-ci | auto

#### Check Runs

name | externalId
-----|-----------
auto (macOS x86_64-apple)                          | [10\|301\|e71b0ddf-dd27-435a-873c-e30f86eea377](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_build/results?buildId=301&view=logs&jobId=1c64c3ff-4c37-56fe-a133-b407354bbfbf)
auto (Linux x86_64-gnu-llvm-6.0)                   | [10\|301\|e71b0ddf-dd27-435a-873c-e30f86eea377](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_build/results?buildId=301&view=logs&jobId=d5810e3a-0d17-5d9d-3d2e-f99007e94ae9)
auto (macOS dist-x86_64-apple)                     | [10\|301\|e71b0ddf-dd27-435a-873c-e30f86eea377](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_build/results?buildId=301&view=logs&jobId=0dc43f6a-414d-5e5c-43cd-8d26a1671d44)
auto (Linux dist-x86_64-linux)                     | [10\|301\|e71b0ddf-dd27-435a-873c-e30f86eea377](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_build/results?buildId=301&view=logs&jobId=75fb7074-5230-5c5b-6df3-8cc660977bc4)
auto (Linux dist-x86_64-linux-alt)                 | [10\|301\|e71b0ddf-dd27-435a-873c-e30f86eea377](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_build/results?buildId=301&view=logs&jobId=396dc680-0b3a-5910-2395-0c692e01f85b)
auto (macOS dist-x86_64-apple-alt)                 | [10\|301\|e71b0ddf-dd27-435a-873c-e30f86eea377](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_build/results?buildId=301&view=logs&jobId=9b18a8e0-d349-5dff-dec8-879f98f28b96)
auto (Linux arm-android)                           | [10\|301\|e71b0ddf-dd27-435a-873c-e30f86eea377](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_build/results?buildId=301&view=logs&jobId=6485e793-6f9a-5940-bdfb-daa9459b44ef)
auto (macOS i686-apple)                            | [10\|301\|e71b0ddf-dd27-435a-873c-e30f86eea377](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_build/results?buildId=301&view=logs&jobId=8ac55db3-a6cf-5386-3be9-05e8c37150db)
auto (Linux armhf-gnu)                             | [10\|301\|e71b0ddf-dd27-435a-873c-e30f86eea377](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_build/results?buildId=301&view=logs&jobId=bedce312-f790-5a16-cf2f-66c91a66d998)
auto (macOS dist-i686-apple)                       | [10\|301\|e71b0ddf-dd27-435a-873c-e30f86eea377](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_build/results?buildId=301&view=logs&jobId=f63b3ca7-cbb3-5440-2716-816dad6162da)
auto (Linux dist-various-1)                        | [10\|301\|e71b0ddf-dd27-435a-873c-e30f86eea377](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_build/results?buildId=301&view=logs&jobId=d83222d8-66d7-5834-04ea-6cca6bcf09dd)
auto (Linux dist-various-2)                        | [10\|301\|e71b0ddf-dd27-435a-873c-e30f86eea377](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_build/results?buildId=301&view=logs&jobId=910a3b72-54f3-5d99-d01c-16c9c22f04ca)
auto (Windows x86_64-msvc-1)                       | [10\|301\|e71b0ddf-dd27-435a-873c-e30f86eea377](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_build/results?buildId=301&view=logs&jobId=a6a2dd6f-5140-5fa9-b933-dfe57be2bdd5)
auto (Linux dist-aarch64-linux)                    | [10\|301\|e71b0ddf-dd27-435a-873c-e30f86eea377](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_build/results?buildId=301&view=logs&jobId=47b783a2-4c27-5eda-9fea-98cf506c800a)
auto (Windows x86_64-msvc-2)                       | [10\|301\|e71b0ddf-dd27-435a-873c-e30f86eea377](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_build/results?buildId=301&view=logs&jobId=c9ea9f88-3fea-5145-c269-3bbafa17f0d5)
auto (Linux dist-android)                          | [10\|301\|e71b0ddf-dd27-435a-873c-e30f86eea377](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_build/results?buildId=301&view=logs&jobId=8459d2f4-1fab-5c91-14f9-f1f91c476a8f)
auto (Windows i686-msvc-1)                         | [10\|301\|e71b0ddf-dd27-435a-873c-e30f86eea377](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_build/results?buildId=301&view=logs&jobId=339a807e-05eb-50a3-f69a-0d7a3a5b2cef)
auto (Linux dist-arm-linux)                        | [10\|301\|e71b0ddf-dd27-435a-873c-e30f86eea377](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_build/results?buildId=301&view=logs&jobId=f7d20715-3f88-509c-241f-58840cdb4e9a)
auto (Windows i686-msvc-2)                         | [10\|301\|e71b0ddf-dd27-435a-873c-e30f86eea377](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_build/results?buildId=301&view=logs&jobId=1c66a17c-d8f0-5a34-b4e6-21cbd74afd4d)
auto (Linux dist-armhf-linux)                      | [10\|301\|e71b0ddf-dd27-435a-873c-e30f86eea377](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_build/results?buildId=301&view=logs&jobId=c548b06d-a0d0-5e80-496f-bb22e203c4bc)
auto (Windows x86_64-msvc-aux)                     | [10\|301\|e71b0ddf-dd27-435a-873c-e30f86eea377](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_build/results?buildId=301&view=logs&jobId=9c50ef33-0f08-5524-430c-de3652601ceb)
auto (Linux dist-armv7-linux)                      | [10\|301\|e71b0ddf-dd27-435a-873c-e30f86eea377](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_build/results?buildId=301&view=logs&jobId=8da03a03-11a9-5a5a-0aa4-8690b1704776)
auto (Windows x86_64-msvc-cargo)                   | [10\|301\|e71b0ddf-dd27-435a-873c-e30f86eea377](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_build/results?buildId=301&view=logs&jobId=34a2f069-38a6-567f-c087-79a147504c7a)
auto (Linux dist-i586-gnu-i586-i686-musl)          | [10\|301\|e71b0ddf-dd27-435a-873c-e30f86eea377](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_build/results?buildId=301&view=logs&jobId=e8f9fbbd-638d-5b4a-16e9-2519b7fb3143)
auto (Windows x86_64-msvc-tools)                   | [10\|301\|e71b0ddf-dd27-435a-873c-e30f86eea377](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_build/results?buildId=301&view=logs&jobId=7fd71ed5-b635-52d1-271f-824e8d5053a7)
auto (Linux dist-i686-freebsd)                     | [10\|301\|e71b0ddf-dd27-435a-873c-e30f86eea377](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_build/results?buildId=301&view=logs&jobId=1e2ea934-bbbb-565e-7dc4-298083bc67af)
auto (Windows i686-mingw-1)                        | [10\|301\|e71b0ddf-dd27-435a-873c-e30f86eea377](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_build/results?buildId=301&view=logs&jobId=5ac1211a-cbe7-52be-dcc2-57e3991fd20c)
auto (Linux dist-i686-linux)                       | [10\|301\|e71b0ddf-dd27-435a-873c-e30f86eea377](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_build/results?buildId=301&view=logs&jobId=e0b986f2-e192-5c4d-4767-e55e6660d4b0)
auto (Windows i686-mingw-2)                        | [10\|301\|e71b0ddf-dd27-435a-873c-e30f86eea377](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_build/results?buildId=301&view=logs&jobId=aac1e68a-9baa-54d2-b80b-75ce793a8506)
auto (Linux dist-mips-linux)                       | [10\|301\|e71b0ddf-dd27-435a-873c-e30f86eea377](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_build/results?buildId=301&view=logs&jobId=51fcf21e-54f2-5c2d-ad57-9f753a576b16)
auto (Windows x86_64-mingw-1)                      | [10\|301\|e71b0ddf-dd27-435a-873c-e30f86eea377](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_build/results?buildId=301&view=logs&jobId=b1e7928f-7d26-57cb-a49e-81353e6c69ce)
auto (Linux dist-mips64-linux)                     | [10\|301\|e71b0ddf-dd27-435a-873c-e30f86eea377](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_build/results?buildId=301&view=logs&jobId=d5182754-3fcf-5f28-a600-5e0776980f69)
auto (Windows x86_64-mingw-2)                      | [10\|301\|e71b0ddf-dd27-435a-873c-e30f86eea377](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_build/results?buildId=301&view=logs&jobId=90f6024d-9735-531d-4933-8983ca347d60)
auto (Linux dist-mips64el-linux)                   | [10\|301\|e71b0ddf-dd27-435a-873c-e30f86eea377](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_build/results?buildId=301&view=logs&jobId=636d1b50-d010-5f91-4479-d9edca6fa764)
auto (Windows dist-x86_64-msvc)                    | [10\|301\|e71b0ddf-dd27-435a-873c-e30f86eea377](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_build/results?buildId=301&view=logs&jobId=10c53b70-9ae7-511a-b369-2febdb4c7298)
auto (Linux dist-mipsel-linux)                     | [10\|301\|e71b0ddf-dd27-435a-873c-e30f86eea377](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_build/results?buildId=301&view=logs&jobId=31980897-bc80-5775-9b1f-7393163984ba)
auto (Windows dist-i686-msvc)                      | [10\|301\|e71b0ddf-dd27-435a-873c-e30f86eea377](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_build/results?buildId=301&view=logs&jobId=5c401de4-424a-5c2d-587f-e5d30c413de5)
auto (Linux dist-powerpc-linux)                    | [10\|301\|e71b0ddf-dd27-435a-873c-e30f86eea377](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_build/results?buildId=301&view=logs&jobId=fd0bd97c-dca3-5d16-5976-7c3893e4446f)
auto (Windows dist-i686-mingw)                     | [10\|301\|e71b0ddf-dd27-435a-873c-e30f86eea377](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_build/results?buildId=301&view=logs&jobId=02078618-5182-5d8f-e6f5-9772c7a38ace)
auto (Linux dist-powerpc64-linux)                  | [10\|301\|e71b0ddf-dd27-435a-873c-e30f86eea377](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_build/results?buildId=301&view=logs&jobId=77fe58e7-c26b-56af-861c-0e6795721952)
auto (Windows dist-x86_64-mingw)                   | [10\|301\|e71b0ddf-dd27-435a-873c-e30f86eea377](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_build/results?buildId=301&view=logs&jobId=cec46d98-28ec-540b-23b7-cb19649abb91)
auto (Linux dist-powerpc64le-linux)                | [10\|301\|e71b0ddf-dd27-435a-873c-e30f86eea377](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_build/results?buildId=301&view=logs&jobId=7295f37b-5319-5bb1-21cd-33d3a3bdcd94)
auto (Windows dist-x86_64-msvc-alt)                | [10\|301\|e71b0ddf-dd27-435a-873c-e30f86eea377](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_build/results?buildId=301&view=logs&jobId=d91b65d8-1798-544d-059f-fe4f3f5f069a)
auto (Linux dist-s390x-linux)                      | [10\|301\|e71b0ddf-dd27-435a-873c-e30f86eea377](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_build/results?buildId=301&view=logs&jobId=964b9902-6b0b-5d50-16f6-f236b826e701)
auto (Linux dist-x86_64-freebsd)                   | [10\|301\|e71b0ddf-dd27-435a-873c-e30f86eea377](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_build/results?buildId=301&view=logs&jobId=4d82e571-5470-589a-fcc8-63a063edfadc)
auto (Linux dist-x86_64-musl)                      | [10\|301\|e71b0ddf-dd27-435a-873c-e30f86eea377](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_build/results?buildId=301&view=logs&jobId=3d16ac53-a9bf-544f-8d9b-74692cf7f1c8)
auto (Linux dist-x86_64-netbsd)                    | [10\|301\|e71b0ddf-dd27-435a-873c-e30f86eea377](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_build/results?buildId=301&view=logs&jobId=a1bbfa4f-3958-53e8-464f-18f9feaa3431)
auto (Linux asmjs)                                 | [10\|301\|e71b0ddf-dd27-435a-873c-e30f86eea377](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_build/results?buildId=301&view=logs&jobId=0e47216c-a892-589a-a5b3-5fa9021bc5b1)
auto (Linux i686-gnu)                              | [10\|301\|e71b0ddf-dd27-435a-873c-e30f86eea377](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_build/results?buildId=301&view=logs&jobId=feabf3e3-d3b7-5218-44c8-94b17c179d97)
auto (Linux i686-gnu-nopt)                         | [10\|301\|e71b0ddf-dd27-435a-873c-e30f86eea377](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_build/results?buildId=301&view=logs&jobId=604eab81-0cf0-52c5-10f8-91bf5e7241d2)
auto (Linux test-various)                          | [10\|301\|e71b0ddf-dd27-435a-873c-e30f86eea377](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_build/results?buildId=301&view=logs&jobId=7f477069-cc2e-5bb5-c142-f030a79bc52a)
auto (Linux x86_64-gnu)                            | [10\|301\|e71b0ddf-dd27-435a-873c-e30f86eea377](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_build/results?buildId=301&view=logs&jobId=06119a86-6aaa-59c5-d776-a1fe7edc9703)
auto (Linux x86_64-gnu-full-bootstrap)             | [10\|301\|e71b0ddf-dd27-435a-873c-e30f86eea377](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_build/results?buildId=301&view=logs&jobId=91cd1eb3-d8d9-5bd4-ec2e-402dc160e397)
auto (Linux x86_64-gnu-aux)                        | [10\|301\|e71b0ddf-dd27-435a-873c-e30f86eea377](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_build/results?buildId=301&view=logs&jobId=e0f1e83e-b4ff-5fea-0524-5e42235a96c8)
auto (Linux x86_64-gnu-tools)                      | [10\|301\|e71b0ddf-dd27-435a-873c-e30f86eea377](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_build/results?buildId=301&view=logs&jobId=e50ab380-190b-535c-8a18-25c988f7577b)
auto (Linux x86_64-gnu-debug)                      | [10\|301\|e71b0ddf-dd27-435a-873c-e30f86eea377](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_build/results?buildId=301&view=logs&jobId=9121965e-722b-5094-4a33-f061e41958d8)
auto (Linux x86_64-gnu-nopt)                       | [10\|301\|e71b0ddf-dd27-435a-873c-e30f86eea377](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_build/results?buildId=301&view=logs&jobId=99ab81d4-3e3b-5299-a10e-bbb9b4eeeaf0)
auto (Linux x86_64-gnu-distcheck)                  | [10\|301\|e71b0ddf-dd27-435a-873c-e30f86eea377](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_build/results?buildId=301&view=logs&jobId=726de84e-3c8c-5512-531d-a9b3bdced5ba)
auto (Linux mingw-check)                           | [10\|301\|e71b0ddf-dd27-435a-873c-e30f86eea377](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_build/results?buildId=301&view=logs&jobId=74054d28-c774-5fab-ecc2-352fe71b230e)
auto                                               | [10\|301\|e71b0ddf-dd27-435a-873c-e30f86eea377](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_build/results?buildId=301)
Travis CI - Branch                                 | [113571511](https://travis-ci.com/rust-lang/rust/builds/113571511)

**Comment by pietroalbini** [comment]
Well, I guess it's fine either way. Your solution is nicer, but the current one works fine. I'd say fixing this is really low priority.
